title: Outsourcing my memory
author: William de Witt
email: sasilverain@hotmail.com
description: Just a placeholder for my thoughts
theme: minima

# social links
twitter_username: silverainza
github_username:  williamdewitt

show_excerpts: true # set to false to remove excerpts on the homepage