title: William de Witt
author: William de Witt
email: sasilverain@hotmail.com
description: | 
  A placeholder for my thoughts, ideas and projects
  that I am currently busy with or want to explore in the furture
baseurl: /blog
url: https://williamdewitt.github.io/

show_excerpts: false

minima:
  social_links:
    twitter: silverainza
    github: williamdewitt
    linkedin: william-de-witt-a4bb9474
    testautomationu: 1a384904

theme: minima

google_analytics: UA-146126900-1

plugins:
  - jekyll-paginate

# Pagination
paginate: 3
paginate_path: blog/page:num/