title: Outsourcing my memory
author: William de Witt
email: sasilverain@hotmail.com
description: Just a placeholder for my thoughts

show_excerpts: false

minima:
  social_links:
    twitter: silverainza
    github: williamdewitt

#header_pages:
# - about.md

theme: minima